//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace KeyCreater
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class dylcEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new dylcEntities object using the connection string found in the 'dylcEntities' section of the application configuration file.
        /// </summary>
        public dylcEntities() : base("name=dylcEntities", "dylcEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new dylcEntities object.
        /// </summary>
        public dylcEntities(string connectionString) : base(connectionString, "dylcEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new dylcEntities object.
        /// </summary>
        public dylcEntities(EntityConnection connection) : base(connection, "dylcEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UserKeyTable> UserKeyTable
        {
            get
            {
                if ((_UserKeyTable == null))
                {
                    _UserKeyTable = base.CreateObjectSet<UserKeyTable>("UserKeyTable");
                }
                return _UserKeyTable;
            }
        }
        private ObjectSet<UserKeyTable> _UserKeyTable;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UserKeyTable EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUserKeyTable(UserKeyTable userKeyTable)
        {
            base.AddObject("UserKeyTable", userKeyTable);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dylcModel", Name="UserKeyTable")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UserKeyTable : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UserKeyTable object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="pDKey">Initial value of the PDKey property.</param>
        /// <param name="regTime">Initial value of the RegTime property.</param>
        /// <param name="enableTime">Initial value of the EnableTime property.</param>
        /// <param name="isForever">Initial value of the IsForever property.</param>
        /// <param name="isUsing">Initial value of the IsUsing property.</param>
        public static UserKeyTable CreateUserKeyTable(global::System.Int64 id, global::System.String userId, global::System.String pDKey, global::System.DateTime regTime, global::System.DateTime enableTime, global::System.Boolean isForever, global::System.Boolean isUsing)
        {
            UserKeyTable userKeyTable = new UserKeyTable();
            userKeyTable.id = id;
            userKeyTable.UserId = userId;
            userKeyTable.PDKey = pDKey;
            userKeyTable.RegTime = regTime;
            userKeyTable.EnableTime = enableTime;
            userKeyTable.IsForever = isForever;
            userKeyTable.IsUsing = isUsing;
            return userKeyTable;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.String _UserId;
        partial void OnUserIdChanging(global::System.String value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PDKey
        {
            get
            {
                return _PDKey;
            }
            set
            {
                OnPDKeyChanging(value);
                ReportPropertyChanging("PDKey");
                _PDKey = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PDKey");
                OnPDKeyChanged();
            }
        }
        private global::System.String _PDKey;
        partial void OnPDKeyChanging(global::System.String value);
        partial void OnPDKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime RegTime
        {
            get
            {
                return _RegTime;
            }
            set
            {
                OnRegTimeChanging(value);
                ReportPropertyChanging("RegTime");
                _RegTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RegTime");
                OnRegTimeChanged();
            }
        }
        private global::System.DateTime _RegTime;
        partial void OnRegTimeChanging(global::System.DateTime value);
        partial void OnRegTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime EnableTime
        {
            get
            {
                return _EnableTime;
            }
            set
            {
                OnEnableTimeChanging(value);
                ReportPropertyChanging("EnableTime");
                _EnableTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EnableTime");
                OnEnableTimeChanged();
            }
        }
        private global::System.DateTime _EnableTime;
        partial void OnEnableTimeChanging(global::System.DateTime value);
        partial void OnEnableTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsForever
        {
            get
            {
                return _IsForever;
            }
            set
            {
                OnIsForeverChanging(value);
                ReportPropertyChanging("IsForever");
                _IsForever = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsForever");
                OnIsForeverChanged();
            }
        }
        private global::System.Boolean _IsForever;
        partial void OnIsForeverChanging(global::System.Boolean value);
        partial void OnIsForeverChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsUsing
        {
            get
            {
                return _IsUsing;
            }
            set
            {
                OnIsUsingChanging(value);
                ReportPropertyChanging("IsUsing");
                _IsUsing = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsUsing");
                OnIsUsingChanged();
            }
        }
        private global::System.Boolean _IsUsing;
        partial void OnIsUsingChanging(global::System.Boolean value);
        partial void OnIsUsingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserMail
        {
            get
            {
                return _UserMail;
            }
            set
            {
                OnUserMailChanging(value);
                ReportPropertyChanging("UserMail");
                _UserMail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserMail");
                OnUserMailChanged();
            }
        }
        private global::System.String _UserMail;
        partial void OnUserMailChanging(global::System.String value);
        partial void OnUserMailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserMobile
        {
            get
            {
                return _UserMobile;
            }
            set
            {
                OnUserMobileChanging(value);
                ReportPropertyChanging("UserMobile");
                _UserMobile = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserMobile");
                OnUserMobileChanged();
            }
        }
        private global::System.String _UserMobile;
        partial void OnUserMobileChanging(global::System.String value);
        partial void OnUserMobileChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserQQ
        {
            get
            {
                return _UserQQ;
            }
            set
            {
                OnUserQQChanging(value);
                ReportPropertyChanging("UserQQ");
                _UserQQ = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserQQ");
                OnUserQQChanged();
            }
        }
        private global::System.String _UserQQ;
        partial void OnUserQQChanging(global::System.String value);
        partial void OnUserQQChanged();

        #endregion
    
    }

    #endregion
    
}
